# arxivの学問領域の指定
subject: 'cat:eess.* OR cat:cond-mat.mes-hall OR cat:physics.app-ph'

# 検索キーワード
keywords:
    quantum: 5
    diamond: 3
    silicon quantum dots: 5
    coherence: 5


# 通知の閾値
score_threshold: 0
