# arxivの学問領域の指定
subject: 'cat:eess.* OR cat:cond-mat.mes-hall OR  cat:cond-mat.mtrl-sci OR cat:physics.app-ph'

# 検索キーワード
keywords:
    quantum: 5
    diamond: 3
    silicon quantum dots: 5
    coherence: 5
    spintronics: 5
    quantum computing: 6
    qubit: 5
    wearable: 5


# 通知の閾値
score_threshold: 0
